# Generated by Django 3.2.8 on 2021-10-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pferd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('line', models.CharField(max_length=300)),
                ('breed', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300)),
                ('img_url', models.TextField()),
                ('video_url', models.TextField()),
            ],
        ),
    ]
